import { describe, it, expect } from 'vitest'
import { eciesEncrypt, eciesDecrypt, fromHex, toHex } from './ecies'

// Known X25519 keypairs — generated by crypto/gen_keys.go
// Alice = sender's keypair (used as ephemeral for determinism in vectors)
// Bob   = receiver's keypair
const ALICE_PRIV = '58205a1c0f0a4c64f7aa98c66e36acbbb77f1b4e7928521979c54e438f175060'
const ALICE_PUB  = '8f96bb249cccc58fd59431ec3f42131685c4b82f93e8f475c2fe71a951777108'
const BOB_PRIV   = '3786026bbd1913f57f8a2d688459f3d85b2147463db38ad79f2b93bce14e0a50'
const BOB_PUB    = '96578ff10ff96d2f58406f8d0f7c6a5f20e7f8b1e4fd030bd3ed86e03ffb2579'

// Go-generated deterministic ciphertext for cross-language verification.
// Produced by crypto/ecies_cross_test.go using (ephemeral=Alice, receiver=Bob,
// nonce=0102030405060708090a0b0c, plaintext="Hello NanoCAS cross-language ECIES test!").
// Format: [ephemeral_pub 32][nonce 12][AES-GCM ciphertext+tag]
const GO_CIPHERTEXT_HEX =
  '8f96bb249cccc58fd59431ec3f42131685c4b82f93e8f475c2fe71a951777108' +
  '0102030405060708090a0b0c' +
  '8cc77eb159ca561a49d1c15395ddb355e802371c58916d1c925ca5d9cc76321a9743e3adb257b4069f992eb5d775aeeb994c043f912115f5'

const PLAINTEXT = 'Hello NanoCAS cross-language ECIES test!'

describe('ECIES cross-language compatibility', () => {
  it('should decrypt Go-encrypted ciphertext with TypeScript', async () => {
    const ciphertext = fromHex(GO_CIPHERTEXT_HEX)
    const decrypted = await eciesDecrypt(BOB_PRIV, ciphertext)
    expect(new TextDecoder().decode(decrypted)).toBe(PLAINTEXT)
  })

  it('should reject decryption with wrong private key', async () => {
    const ciphertext = fromHex(GO_CIPHERTEXT_HEX)
    await expect(eciesDecrypt(ALICE_PRIV, ciphertext)).rejects.toThrow()
  })

  it('should reject too-short payload', async () => {
    await expect(
      eciesDecrypt(BOB_PRIV, new Uint8Array(10))
    ).rejects.toThrow('ECIES payload too short')
  })
})

describe('ECIES TypeScript round-trip', () => {
  it('should encrypt and decrypt successfully', async () => {
    const plaintext = new TextEncoder().encode(PLAINTEXT)
    const ciphertext = await eciesEncrypt(BOB_PUB, plaintext)
    expect(ciphertext.length).toBe(plaintext.length + 32 + 12 + 16) // pub + nonce + gcm tag
    const decrypted = await eciesDecrypt(BOB_PRIV, ciphertext)
    expect(new TextDecoder().decode(decrypted)).toBe(PLAINTEXT)
  })

  it('should produce different ciphertexts each time (random ephemeral + nonce)', async () => {
    const plaintext = new TextEncoder().encode('determinism check')
    const [c1, c2] = await Promise.all([
      eciesEncrypt(BOB_PUB, plaintext),
      eciesEncrypt(BOB_PUB, plaintext),
    ])
    expect(toHex(c1)).not.toBe(toHex(c2))
  })

  it('should fail with wrong private key (random ciphertext)', async () => {
    const plaintext = new TextEncoder().encode('test data')
    const ciphertext = await eciesEncrypt(BOB_PUB, plaintext)
    await expect(eciesDecrypt(ALICE_PRIV, ciphertext)).rejects.toThrow()
  })
})

describe('ECIES key handling', () => {
  it('fromHex and toHex round-trip', () => {
    const hex = 'deadbeef0102030405060708090a0b0c'
    const bytes = fromHex(hex)
    expect(toHex(bytes)).toBe(hex)
  })
})
